export enum Identifiers {
	ArgsMissing = 'argsMissing',
	ArgsUnavailable = 'argsUnavailable',

	ArgumentBooleanError = 'booleanError',
	ArgumentChannelError = 'channelError',
	ArgumentDateError = 'dateError',
	ArgumentDateTooEarly = 'dateTooEarly',
	ArgumentDateTooFar = 'dateTooFar',
	ArgumentDMChannelError = 'dmChannelError',
	ArgumentEmojiError = 'emojiError',
	ArgumentFloatError = 'floatError',
	ArgumentFloatTooLarge = 'floatTooLarge',
	ArgumentFloatTooSmall = 'floatTooSmall',
	ArgumentGuildError = 'guildError',
	ArgumentGuildCategoryChannelError = 'categoryChannelError',
	ArgumentGuildChannelError = 'guildChannelError',
	ArgumentGuildChannelMissingGuildError = 'guildChannelMissingGuildError',
	ArgumentGuildNewsChannelError = 'guildNewsChannelError',
	ArgumentGuildNewsThreadChannelError = 'guildNewsChannelError',
	ArgumentGuildPrivateThreadChannelError = 'guildPrivateThreadChannelError',
	ArgumentGuildPublicThreadChannelError = 'guildPublicThreadChannelError',
	ArgumentGuildStageVoiceChannelError = 'guildStageVoiceChannelError',
	ArgumentGuildTextChannelError = 'guildTextChannelError',
	ArgumentGuildThreadChannelError = 'guildThreadChannelError',
	ArgumentGuildVoiceChannelError = 'guildVoiceChannelError',
	ArgumentHyperlinkError = 'hyperlinkError',
	ArgumentIntegerError = 'integerError',
	ArgumentIntegerTooLarge = 'integerTooLarge',
	ArgumentIntegerTooSmall = 'integerTooSmall',
	ArgumentMemberError = 'memberError',
	ArgumentMemberMissingGuild = 'memberMissingGuild',
	ArgumentMessageError = 'messageError',
	ArgumentNumberError = 'numberError',
	ArgumentNumberTooLarge = 'numberTooLarge',
	ArgumentNumberTooSmall = 'numberTooSmall',
	ArgumentRoleError = 'roleError',
	ArgumentRoleMissingGuild = 'roleMissingGuild',
	ArgumentStringTooLong = 'stringTooLong',
	ArgumentStringTooShort = 'stringTooShort',
	ArgumentUserError = 'userError',
	ArgumentEnumEmptyError = 'enumEmptyError',
	ArgumentEnumError = 'enumError',

	CommandDisabled = 'commandDisabled',

	PreconditionCooldown = 'preconditionCooldown',
	PreconditionDMOnly = 'preconditionDmOnly',
	PreconditionGuildNewsOnly = 'preconditionGuildNewsOnly',
	PreconditionGuildNewsThreadOnly = 'preconditionGuildNewsThreadOnly',
	PreconditionGuildOnly = 'preconditionGuildOnly',
	PreconditionGuildPrivateThreadOnly = 'preconditionGuildPrivateThreadOnly',
	PreconditionGuildPublicThreadOnly = 'preconditionGuildPublicThreadOnly',
	PreconditionGuildTextOnly = 'preconditionGuildTextOnly',
	PreconditionGuildVoiceOnly = 'preconditionGuildVoiceOnly',
	PreconditionNSFW = 'preconditionNsfw',
	PreconditionClientPermissions = 'preconditionClientPermissions',
	PreconditionClientPermissionsNoClient = 'preconditionClientPermissionsNoClient',
	PreconditionClientPermissionsNoPermissions = 'preconditionClientPermissionsNoPermissions',
	PreconditionUserPermissions = 'preconditionUserPermissions',
	PreconditionUserPermissionsNoPermissions = 'preconditionUserPermissionsNoPermissions',
	PreconditionThreadOnly = 'preconditionThreadOnly',

	PreconditionUnavailable = 'preconditionUnavailable',

	PreconditionMissingMessageHandler = 'preconditionMissingMessageHandler',
	PreconditionMissingChatInputHandler = 'preconditionMissingChatInputHandler',
	PreconditionMissingContextMenuHandler = 'preconditionMissingContextMenuHandler'
}
