name: Publish

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  PublishPackage:
    name: Publish @sapphire/framework
    uses: sapphiredev/.github/.github/workflows/reusable-publish.yml@main
    with:
      project-name: '@sapphire/framework'
    secrets:
      SKYRA_TOKEN: ${{ secrets.SKYRA_TOKEN }}
